- name: Install packages
  package: name={{item}}
  with_items:
    - htop
    - discord
    - element-desktop
    - code
    - alacritty
    - neovim
    - fish
  #when: ansible_facts['os_family']|lower == 'archlinux'

- name: Change shell
  user: 
    name: onigiri
    shell: /usr/bin/fish
