- name: Install packages
  package: name={{item}}
  with_items:
    - htop
    - discord
    - zsh
    - element-desktop
    - code
    - alacritty
      #when: ansible_facts['os_family']|lower == 'archlinux'
