- name: Change shell
  user: 
    name: "onigiri"
    shell: /usr/bin/zsh

- name: Download zim installer
  get_url: 
    url: https://raw.githubusercontent.com/zimfw/install/master/install.zsh 
    dest: /home/onigiri/Downloads/zim-install.zsh
    mode: 0755

- name: Execute zim-install.zsh
  command: "zsh /home/onigiri/Downloads/zim-install.zsh"

- name: Remove zim-install.zsh
  file: path=/home/onigiri/Downloads/zim-install.zsh state=absent

