- name: Change shell
  user: 
    name: "onigiri"
    shell: /usr/bin/zsh

- name: Download zimfw installer
  get_url: 
    url: https://raw.githubusercontent.com/zimfw/install/master/install.zsh 
    dest: /home/onigiri/Downloads/
    mode: 0755

- name: Execute zimfw-install.sh
  shell: /tmp/zimfw-install.sh

- name: Remove zimfw-install.sh
  file: path=/tmp/zimfw-install.sh state=absent

