- name: Change shell
  command: "chsh -s /usr/bin/zsh"

- name: Download zimfw installer
  get_url: url=https://raw.githubusercontent.com/zimfw/install/master/install.zsh dest=/tmp/zimfw-install.sh

- name: Execute zimfw-installer.sh
  shell: /tmp/zimfw-install.sh

- name: Remove zimfw-installer.sh
  file: path=/tmp/zimfw-install.sh state=absent

