- name: Change shell
  user: 
    name: "onigiri"
    shell: /usr/bin/zsh

- name: Download zimfw installer
  get_url: 
    url: https://raw.githubusercontent.com/zimfw/install/master/install.zsh 
    dest: /home/onigiri/Downloads/zimfw-install.zsh
    mode: 0755

- name: Execute zimfw-install.sh
  command: "zsh /home/onigiri/Downloads/zimfw-install.zsh"

- name: Remove zimfw-install.sh
  file: path=/home/onigiri/Downloads/zimfw-install.zsh state=absent

