- name: Download zimfw installer
  get_url: https://raw.githubusercontent.com/zimfw/install/master/install.zsh dest=/tmp/zimfw-install.sh

- name: Execute zimfw-installer.sh
  shell: /tmp/zimfw-installer.sh

- name: Remove zimfw-installer.sh
  file: path=/tmp/zimfw-installer.sh state=absent

